services:
  postgres:
    profiles: [ postgres, postgres-all, all, all-no-ui, ci ]
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=moneywave
      - POSTGRES_PASSWORD=Password12!
    ports:
      - "5432:5432"

  pgadmin:
    profiles: [ postgres-ui, postgres-all, all ]
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"

  jaeger:
    profiles: [ otel, otel-all, all ]
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  eventstore.db:
    profiles: [ eventstoredb, eventstoredb-all, all, all-no-ui, ci ]
    image: eventstore/eventstore:24.6.0-bookworm-slim
    # use this image if you're running ARM-based proc like Apple M1
    # image: eventstore/eventstore:23.10.0-alpha-arm64v8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  moneywave.api:
    image: moneywave.api
    build:
      context: .
      dockerfile: MoneyWave.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - EventStore__ConnectionString=esdb://eventstore.db:2113?tls=false
      - Marten__ConnectionString=PORT = 5432; HOST = postgres; TIMEOUT = 15; POOLING = True; MINPOOLSIZE = 1; MAXPOOLSIZE = 100; COMMANDTIMEOUT = 20; DATABASE = 'moneywave'; PASSWORD = 'Password12!'; USER ID = 'postgres'
      - Marten__WriteModelSchema=esdb_money_wave_write
      - Marten__ReadModelSchema=esdb_money_wave_read

volumes:
  postgres:
  pgadmin:
  eventstore-volume-data:
  eventstore-volume-logs:
